"""Shared type stub for the unit names that ``make_system`` creates
dynamically via ``globals().update(...)``.

Static analyzers (Pylance/Pyright/mypy) cannot see runtime-populated
names, so they are declared here once and re-exported by the package
``__init__`` and every ``systems/*`` module through a matching ``.pyi``.

Generated by ``_gen_stubs.py`` from the package's runtime surface, which
mirrors the keys of ``baseUnits._factors``. Regenerate if those change.
"""

__all__ = [
    "BASE",
    "g",
    "C",
    "F",
    "GPa",
    "HP",
    "J",
    "K",
    "MN",
    "MPa",
    "MW",
    "N",
    "N_per_m3",
    "N_per_mm3",
    "Pa",
    "W",
    "Wh",
    "atm",
    "bar",
    "cal",
    "cm",
    "day",
    "degree",
    "dyne",
    "eV",
    "ft",
    "gr",
    "gr_per_cm3",
    "gram",
    "h",
    "inches",
    "kJ",
    "kN",
    "kN_per_m3",
    "kPa",
    "kW",
    "kWh",
    "kcal",
    "kg",
    "kg_per_m3",
    "kgf",
    "kgf_cm2",
    "kgf_per_m3",
    "kip",
    "km",
    "ksi",
    "lb",
    "lb_per_ft3",
    "lbf",
    "m",
    "mJ",
    "mJ_s",
    "mg",
    "mile",
    "minutes",
    "mm",
    "month",
    "oz",
    "psi",
    "rad",
    "radian",
    "s",
    "tf",
    "tonne",
    "tonne_per_m3",
    "tonne_per_mm3",
    "week",
    "yard",
    "year",
]

BASE: str
g: float
C: float
F: float
GPa: float
HP: float
J: float
K: float
MN: float
MPa: float
MW: float
N: float
N_per_m3: float
N_per_mm3: float
Pa: float
W: float
Wh: float
atm: float
bar: float
cal: float
cm: float
day: float
degree: float
dyne: float
eV: float
ft: float
gr: float
gr_per_cm3: float
gram: float
h: float
inches: float
kJ: float
kN: float
kN_per_m3: float
kPa: float
kW: float
kWh: float
kcal: float
kg: float
kg_per_m3: float
kgf: float
kgf_cm2: float
kgf_per_m3: float
kip: float
km: float
ksi: float
lb: float
lb_per_ft3: float
lbf: float
m: float
mJ: float
mJ_s: float
mg: float
mile: float
minutes: float
mm: float
month: float
oz: float
psi: float
rad: float
radian: float
s: float
tf: float
tonne: float
tonne_per_m3: float
tonne_per_mm3: float
week: float
yard: float
year: float
