"""One-shot generator for the baseUnits type stubs (.pyi).

Run from the repo root. Derives the exported names from the *runtime* package
(the source of truth, since make_system populates them dynamically) and writes:

  src/baseUnits/_unit_consts.pyi   - shared declarations of every unit name
  src/baseUnits/__init__.pyi       - package surface (re-export + submodules)
  src/baseUnits/systems/<sys>.pyi  - one thin re-export per system module

Temporary tooling; safe to delete after the stubs are committed.
"""

from __future__ import annotations

import types

import baseUnits

SYSTEMS = ["N_mm_s", "N_m_s", "kN_m_s", "kip_in_s", "kgf_m_s", "dyne_cm_s"]


def exported_names() -> list[str]:
    names = [
        k
        for k, v in vars(baseUnits).items()
        if not k.startswith("__") and not isinstance(v, types.ModuleType)
    ]
    # BASE and g first for readability, then the rest sorted.
    rest = sorted(n for n in names if n not in ("BASE", "g"))
    return ["BASE", "g", *rest]


def annotation(name: str) -> str:
    return "str" if name == "BASE" else "float"


def write(path: str, text: str) -> None:
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    print(f"wrote {path} ({len(text)} bytes)")


def main() -> None:
    names = exported_names()

    all_block = "__all__ = [\n" + "".join(f'    "{n}",\n' for n in names) + "]\n"
    decls = "".join(f"{n}: {annotation(n)}\n" for n in names)
    consts = (
        '"""Shared type stub for the unit names that ``make_system`` creates\n'
        "dynamically via ``globals().update(...)``.\n\n"
        "Static analyzers (Pylance/Pyright/mypy) cannot see runtime-populated\n"
        "names, so they are declared here once and re-exported by the package\n"
        "``__init__`` and every ``systems/*`` module through a matching ``.pyi``.\n\n"
        "Generated by ``_gen_stubs.py`` from the package's runtime surface, which\n"
        "mirrors the keys of ``baseUnits._factors``. Regenerate if those change.\n"
        '"""\n\n'
        + all_block
        + "\n"
        + decls
    )
    write("src/baseUnits/_unit_consts.pyi", consts)

    init = (
        '"""Type stub for :mod:`baseUnits` (see ``_unit_consts.pyi``)."""\n\n'
        "from . import checked as checked\n"
        "from . import systems as systems\n"
        "from ._unit_consts import *\n"
    )
    write("src/baseUnits/__init__.pyi", init)

    for sysname in SYSTEMS:
        doc = f'"""Type stub for baseUnits.systems.{sysname} (see _unit_consts.pyi)."""'
        stub = doc + "\n\nfrom .._unit_consts import *\n"
        write(f"src/baseUnits/systems/{sysname}.pyi", stub)

    print(f"OK names={len(names)} systems={len(SYSTEMS)}")


if __name__ == "__main__":
    main()
